language: python
python:
  - 2.7
  - 3.4
  - 3.5
script: python setup.py test
before_install:
  - pip install --upgrade pytest pytest-cov python-coveralls
branches:
  only:
    - master
after_success:
  - coveralls
